title: Math Test
email: t.uemura00@gmail.com
description: >-
  Test page for Krater, a template for math-intensive Jekyll websites.
baseurl: &baseurl "/math-test"
url: "https://uemurax.github.io/"
twitter_username: t_uemura669101
github_username: uemurax

safe: false

source: .

theme: minima

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: null # disable math engine and let the client side use KaTeX for simple LaTeX
  parse_block_html: true

katex:
  delimiters:
    - { left: "$", right: "$", display: false }
    - { left: "$$", right: "$$", display: true }
    - { left: "\\(", right: "\\)", display: false }
    - { left: "\\[", right: "\\]", display: true }

antex:
  url_path_prefix: *baseurl
  aliases: # disable most aliases and use server side AnTeX only for complex LaTeX
    display_math: false
    inline_math: false
    inline_macro: false
  preamble: >-
    \usepackage{tikz}
    \usetikzlibrary{cd}
  commands:
    latexmk:
      command:
        - "TEXINPUTS=./antex-macros/:${TEXINPUTS}"
        - "latexmk"
        - "-dvi"
        - "-output-directory={{ dir.work }}"
        - "{{ file.tex }}"

# Macros for both katex and antex
tex_macros:
  "\\cat":
    body: "\\mathcal{#1}"
    nargs: 1

header_pages:
  - changelog.md
  - search.md

collections:
  lectures:
    output: true
  nodes:
    output: true

defaults:
  - scope:
      type: lectures
    values:
      taxon: lecture

sheafy:
  references:
    matchers:
      - !ruby/regexp /{%\s*node "(?<slug>.+?)"/
  taxa:
    definition:
      layout: sheafy/tree/default
      sublayout: sheafy/node/result
      genus: Definition
      clicker: result
    section:
      layout: sheafy/tree/default
      sublayout: sheafy/node/section
      genus: Section
      clicker: section
    theorem:
      layout: sheafy/tree/default
      sublayout: sheafy/node/proposition
      genus: Theorem
      clicker: result
    proof:
      layout: sheafy/tree/default
      sublayout: sheafy/node/proof
      genus: Proof
      clicker: result
    lecture:
      layout: sheafy/tree/default
      sublayout: sheafy/node/section
      genus: Lecture
      clicker: lecture

scholar:
  bibliography: references.bib
  details_layout: bibliography-details.html
  details_permalink: ':details_dir/:key:extension'
  details_link: '[Details]'
  bibliography_template: bibliography-item
  style: apa-no-doi-no-issue

git_log:
  path:
    - "_lectures/*.md"
    - "_nodes/*.md"

exclude:
  # non default values:
  - README.md
  - krater.png
  - bin/
  - antex-macros/
  - src/
  - Makefile
  - _bibliography/
  # default values:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

include:
  - .nojekyll # tells GHP not to run Jekyll again on the build
