title: Math Test
email: t.uemura00@gmail.com
description: >-
  Test page for Krater, a template for math-intensive Jekyll websites.
baseurl: &baseurl "/math-test"
url: "https://uemurax.github.io/"
twitter_username: t_uemura669101
github_username: uemurax

theme: minima

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: null # disable math engine and let the client side use KaTeX for simple LaTeX
  parse_block_html: true

katex:
  delimiters:
    - { left: "$", right: "$", display: false }
    - { left: "$$", right: "$$", display: true }
    - { left: "\\(", right: "\\)", display: false }
    - { left: "\\[", right: "\\]", display: true }
  # Macros are defined in _includes/katex-macros.json

antex:
  url_path_prefix: *baseurl
  aliases: # disable most aliases and use server side AnTeX only for complex LaTeX
    display_math: false
    inline_math: false
    inline_macro: false
  preamble: >-
    \usepackage{simple-macros}
    \usepackage{tikz}
    \usetikzlibrary{cd}
  commands:
    latexmk:
      command:
        - "TEXINPUTS=./antex-macros/:${TEXINPUTS}"
        - "latexmk"
        - "-dvi"
        - "-output-directory={{ dir.work }}"
        - "{{ file.tex }}"

collections:
  lectures:
    output: true
  nodes:
    output: true

sheafy:
  taxa:
    definition:
      layout: default
      sublayout: sheafy/node/result
      genus: Definition
      clicker: result
    section:
      layout: default
      sublayout: sheafy/node/section
      genus: Section
      clicker: section
    theorem:
      layout: default
      sublayout: sheafy/node/result
      genus: Theorem
      clicker: result

exclude:
  # non default values:
  - README.md
  - krater.png
  - bin/
  - antex-macros/
  - src/
  - Makefile
  # default values:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

include:
  - .nojekyll # tells GHP not to run Jekyll again on the build
