name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build
        uses: ./.github/actions/build

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        if: success()
        with:
          build_dir: _site
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
